content:
  - name: posts
    label: 記事一覧
    path: _posts
    type: collection
    layout: body
    fields:
      - name: title
        label: タイトル
        type: string
        required: true
      - name: date
        label: 公開日時
        type: date
        required: true
      - name: layout
        label: レイアウト
        type: string
        default: post
        required: true
      - name: author
        label: 著者
        type: string
        default: Rabbitflower
        required: true
      - name: image
        label: サムネイル画像URL
        type: string
        default: assets/images/webp/didyouknow.svg
        required: false
      - name: categories
        label: カテゴリ
        type: list
        required: false
      - name: tags
        label: タグ
        type: list
        required: false
      - name: body
        label: 本文
        type: rich-text
        media_url: /assets/images # ← 本文にドロップした画像の保存先を追加しました！
        required: true