content:
  - name: posts
    label: 記事一覧
    path: _posts
    type: collection
    layout: body
    fields:
      - name: title
        label: タイトル
        type: string
        required: true
      - name: date
        label: 公開日時
        type: date
        required: true
      - name: layout
        label: レイアウト
        type: string
        default: post
        required: true
      - name: author
        label: 著者
        type: string
        default: Rabbitflower # 自動で「Rabbitflower」が入るようにしています
        required: true
      - name: image
        label: サムネイル画像
        type: image
        # ↓お使いのwebpフォルダに自動で保存されるように調整しました
        media_url: /assets/images/webp
        required: false
      - name: categories
        label: カテゴリ（カンマ区切り、または個別入力）
        type: list
        required: false
      - name: tags
        label: タグ
        type: list
        required: false
      - name: body
        label: 本文
        type: rich-text
        required: true